drop table if exists Hidden_Village,
                     Destroyed_village,
                     Country,
                     Country_lord,
                     Citizen,
                     Parents,
                     Clan,
                     Ninja,
                     Ninja_parents,
                     Biju,
                     Ranked_ninja,
                     Ninjas_rank,
                     "Type",
                     Additional_type,
                     Technic_rank,
                     Technic,
                     Ninja_technic,
                     War,
                     Battle cascade;

